// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int character_0_f940cdd672670304c88aa319a24efa31Index = 0;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "character_0_f940cdd672670304c88aa319a24efa31", 0 },

		};
	}
}
