// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct character_0_id0_UnityEngine__char_46_Animator_4031187718391344175 : ICoherenceComponentData
	{
		public float Blend;
		public float moveX;
		public float moveY;
		public bool isMoving;
		public bool isShooting;

		public override string ToString()
		{
			return $"character_0_id0_UnityEngine__char_46_Animator_4031187718391344175(Blend: {Blend}, moveX: {moveX}, moveY: {moveY}, isMoving: {isMoving}, isShooting: {isShooting})";
		}

		public uint GetComponentType() => Definition.Internalcharacter_0_id0_UnityEngine__char_46_Animator_4031187718391344175;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (character_0_id0_UnityEngine__char_46_Animator_4031187718391344175)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				Blend = other.Blend;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				moveX = other.moveX;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				moveY = other.moveY;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				isMoving = other.isMoving;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				isShooting = other.isShooting;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");

		}

		public static void Serialize(character_0_id0_UnityEngine__char_46_Animator_4031187718391344175 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.Blend, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.moveX, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.moveY, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteBool(data.isMoving);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteBool(data.isShooting);
			}
			mask >>= 1;
		}

		public static (character_0_id0_UnityEngine__char_46_Animator_4031187718391344175, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new character_0_id0_UnityEngine__char_46_Animator_4031187718391344175();
	
			if (bitStream.ReadMask())
			{
				val.Blend = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.moveX = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.moveY = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000100;
			}
			if (bitStream.ReadMask())
			{
				val.isMoving = bitStream.ReadBool();
				mask |= 0b00000000000000000000000000001000;
			}
			if (bitStream.ReadMask())
			{
				val.isShooting = bitStream.ReadBool();
				mask |= 0b00000000000000000000000000010000;
			}
			return (val, mask, null);
		}
		public static (character_0_id0_UnityEngine__char_46_Animator_4031187718391344175, uint, uint?) DeserializeArchetypecharacter_0_f940cdd672670304c88aa319a24efa31_character_0_id0_UnityEngine__char_46_Animator_4031187718391344175_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new character_0_id0_UnityEngine__char_46_Animator_4031187718391344175();
			if (bitStream.ReadMask())
			{
				val.Blend = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.moveX = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.moveY = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000100;
			}
			if (bitStream.ReadMask())
			{
				val.isMoving = bitStream.ReadBool();
				mask |= 0b00000000000000000000000000001000;
			}
			if (bitStream.ReadMask())
			{
				val.isShooting = bitStream.ReadBool();
				mask |= 0b00000000000000000000000000010000;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as character_0_id0_UnityEngine__char_46_Animator_4031187718391344175?;
	
		}
	}
}