// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_f940cdd672670304c88aa319a24efa31_2f6f461d_742c_4bb3_bdc0_baf9665b9d4a : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(coherenceSync.coherencePosition);
			set => coherenceSync.coherencePosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldPosition)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_f940cdd672670304c88aa319a24efa31_614464e6_fbad_4b34_a022_0674420fd385 : RotationBinding
	{
		public override string CoherenceComponentName => "WorldOrientation";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get => (Quaternion)(UnityEngine.Quaternion)(coherenceSync.coherenceRotation);
			set => coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value);
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldOrientation)coherenceComponent).value;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldOrientation)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldOrientation();
		}
	}

	public class Binding_f940cdd672670304c88aa319a24efa31_2e509c15_2aa5_4b45_b25a_60c9f7b02e98 : ScaleBinding
	{
		public override string CoherenceComponentName => "GenericScale";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(coherenceSync.coherenceLocalScale);
			set => coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((GenericScale)coherenceComponent).value;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (GenericScale)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new GenericScale();
		}
	}

	public class Binding_f940cdd672670304c88aa319a24efa31_cb530413_3200_4cab_896e_95e6835c57ba : FloatAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "character_0_id0_UnityEngine__char_46_Animator_4031187718391344175";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override float Value
		{
			get => (float)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, (value));
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((character_0_id0_UnityEngine__char_46_Animator_4031187718391344175)coherenceComponent).Blend;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (character_0_id0_UnityEngine__char_46_Animator_4031187718391344175)coherenceComponent;
			update.Blend = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new character_0_id0_UnityEngine__char_46_Animator_4031187718391344175();
		}
	}

	public class Binding_f940cdd672670304c88aa319a24efa31_0435f6bc_40e9_4e96_852d_9b229e7b6d47 : FloatAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "character_0_id0_UnityEngine__char_46_Animator_4031187718391344175";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override float Value
		{
			get => (float)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, (value));
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((character_0_id0_UnityEngine__char_46_Animator_4031187718391344175)coherenceComponent).moveX;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (character_0_id0_UnityEngine__char_46_Animator_4031187718391344175)coherenceComponent;
			update.moveX = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new character_0_id0_UnityEngine__char_46_Animator_4031187718391344175();
		}
	}

	public class Binding_f940cdd672670304c88aa319a24efa31_99a2cc71_113d_4933_b7c7_c477c42f98c2 : FloatAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "character_0_id0_UnityEngine__char_46_Animator_4031187718391344175";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override float Value
		{
			get => (float)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, (value));
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((character_0_id0_UnityEngine__char_46_Animator_4031187718391344175)coherenceComponent).moveY;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (character_0_id0_UnityEngine__char_46_Animator_4031187718391344175)coherenceComponent;
			update.moveY = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new character_0_id0_UnityEngine__char_46_Animator_4031187718391344175();
		}
	}

	public class Binding_f940cdd672670304c88aa319a24efa31_630a902c_4eb0_46b8_a2ac_e4905a184aa8 : BoolAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "character_0_id0_UnityEngine__char_46_Animator_4031187718391344175";

		public override uint FieldMask => 0b00000000000000000000000000001000;

		public override bool Value
		{
			get => (bool)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, (value));
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((character_0_id0_UnityEngine__char_46_Animator_4031187718391344175)coherenceComponent).isMoving;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (character_0_id0_UnityEngine__char_46_Animator_4031187718391344175)coherenceComponent;
			update.isMoving = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new character_0_id0_UnityEngine__char_46_Animator_4031187718391344175();
		}
	}

	public class Binding_f940cdd672670304c88aa319a24efa31_d7c993b4_fbe9_462f_82ab_7a78269d1b49 : BoolAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "character_0_id0_UnityEngine__char_46_Animator_4031187718391344175";

		public override uint FieldMask => 0b00000000000000000000000000010000;

		public override bool Value
		{
			get => (bool)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, (value));
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((character_0_id0_UnityEngine__char_46_Animator_4031187718391344175)coherenceComponent).isShooting;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (character_0_id0_UnityEngine__char_46_Animator_4031187718391344175)coherenceComponent;
			update.isShooting = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new character_0_id0_UnityEngine__char_46_Animator_4031187718391344175();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'character_0' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSynccharacter_0_id0 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSynccharacter_0_id0>();
			if (coherenceSync.TryGetBindingByGuid("2f6f461d-742c-4bb3-bdc0-baf9665b9d4a", "position", out Binding InternalWorldPosition_Translation_value))
			{
				var clone = new Binding_f940cdd672670304c88aa319a24efa31_2f6f461d_742c_4bb3_bdc0_baf9665b9d4a();
				InternalWorldPosition_Translation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldPosition_Translation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
			if (coherenceSync.TryGetBindingByGuid("614464e6-fbad-4b34-a022-0674420fd385", "rotation", out Binding InternalWorldOrientation_Rotation_value))
			{
				var clone = new Binding_f940cdd672670304c88aa319a24efa31_614464e6_fbad_4b34_a022_0674420fd385();
				InternalWorldOrientation_Rotation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldOrientation_Rotation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}
			if (coherenceSync.TryGetBindingByGuid("2e509c15-2aa5-4b45-b25a-60c9f7b02e98", "localScale", out Binding InternalGenericScale_GenericScale_value))
			{
				var clone = new Binding_f940cdd672670304c88aa319a24efa31_2e509c15_2aa5_4b45_b25a_60c9f7b02e98();
				InternalGenericScale_GenericScale_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalGenericScale_GenericScale_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).localScale");
			}
			if (coherenceSync.TryGetBindingByGuid("cb530413-3200-4cab-896e-95e6835c57ba", "Blend", out Binding Internalcharacter_0_id0_UnityEngine__char_46_Animator_4031187718391344175_character_0_id0_UnityEngine__char_46_Animator_4031187718391344175_Blend))
			{
				var clone = new Binding_f940cdd672670304c88aa319a24efa31_cb530413_3200_4cab_896e_95e6835c57ba();
				Internalcharacter_0_id0_UnityEngine__char_46_Animator_4031187718391344175_character_0_id0_UnityEngine__char_46_Animator_4031187718391344175_Blend.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(Internalcharacter_0_id0_UnityEngine__char_46_Animator_4031187718391344175_character_0_id0_UnityEngine__char_46_Animator_4031187718391344175_Blend)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).Blend");
			}
			if (coherenceSync.TryGetBindingByGuid("0435f6bc-40e9-4e96-852d-9b229e7b6d47", "moveX", out Binding Internalcharacter_0_id0_UnityEngine__char_46_Animator_4031187718391344175_character_0_id0_UnityEngine__char_46_Animator_4031187718391344175_moveX))
			{
				var clone = new Binding_f940cdd672670304c88aa319a24efa31_0435f6bc_40e9_4e96_852d_9b229e7b6d47();
				Internalcharacter_0_id0_UnityEngine__char_46_Animator_4031187718391344175_character_0_id0_UnityEngine__char_46_Animator_4031187718391344175_moveX.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(Internalcharacter_0_id0_UnityEngine__char_46_Animator_4031187718391344175_character_0_id0_UnityEngine__char_46_Animator_4031187718391344175_moveX)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).moveX");
			}
			if (coherenceSync.TryGetBindingByGuid("99a2cc71-113d-4933-b7c7-c477c42f98c2", "moveY", out Binding Internalcharacter_0_id0_UnityEngine__char_46_Animator_4031187718391344175_character_0_id0_UnityEngine__char_46_Animator_4031187718391344175_moveY))
			{
				var clone = new Binding_f940cdd672670304c88aa319a24efa31_99a2cc71_113d_4933_b7c7_c477c42f98c2();
				Internalcharacter_0_id0_UnityEngine__char_46_Animator_4031187718391344175_character_0_id0_UnityEngine__char_46_Animator_4031187718391344175_moveY.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(Internalcharacter_0_id0_UnityEngine__char_46_Animator_4031187718391344175_character_0_id0_UnityEngine__char_46_Animator_4031187718391344175_moveY)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).moveY");
			}
			if (coherenceSync.TryGetBindingByGuid("630a902c-4eb0-46b8-a2ac-e4905a184aa8", "isMoving", out Binding Internalcharacter_0_id0_UnityEngine__char_46_Animator_4031187718391344175_character_0_id0_UnityEngine__char_46_Animator_4031187718391344175_isMoving))
			{
				var clone = new Binding_f940cdd672670304c88aa319a24efa31_630a902c_4eb0_46b8_a2ac_e4905a184aa8();
				Internalcharacter_0_id0_UnityEngine__char_46_Animator_4031187718391344175_character_0_id0_UnityEngine__char_46_Animator_4031187718391344175_isMoving.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(Internalcharacter_0_id0_UnityEngine__char_46_Animator_4031187718391344175_character_0_id0_UnityEngine__char_46_Animator_4031187718391344175_isMoving)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).isMoving");
			}
			if (coherenceSync.TryGetBindingByGuid("d7c993b4-fbe9-462f-82ab-7a78269d1b49", "isShooting", out Binding Internalcharacter_0_id0_UnityEngine__char_46_Animator_4031187718391344175_character_0_id0_UnityEngine__char_46_Animator_4031187718391344175_isShooting))
			{
				var clone = new Binding_f940cdd672670304c88aa319a24efa31_d7c993b4_fbe9_462f_82ab_7a78269d1b49();
				Internalcharacter_0_id0_UnityEngine__char_46_Animator_4031187718391344175_character_0_id0_UnityEngine__char_46_Animator_4031187718391344175_isShooting.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(Internalcharacter_0_id0_UnityEngine__char_46_Animator_4031187718391344175_character_0_id0_UnityEngine__char_46_Animator_4031187718391344175_isShooting)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).isShooting");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSynccharacter_0_id0] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
